# Generated by Django 4.2.19 on 2025-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patientprofile_blood_group_patientprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
    ]
