# Generated by Django 4.2.19 on 2025-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_heartdiseaseprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
    ]
